# Generated by Django 3.1.1 on 2020-10-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
