# Generated by Django 3.1.1 on 2020-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_county',
            field=models.CharField(blank=True, default='county', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_full_name',
            field=models.CharField(blank=True, default='full name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_phone_number',
            field=models.CharField(blank=True, default='0777777', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_postcode',
            field=models.CharField(blank=True, default='postcode', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_street_address1',
            field=models.CharField(blank=True, default='sa1', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_street_address2',
            field=models.CharField(blank=True, default='sa2', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_town_or_city',
            field=models.CharField(blank=True, default='town', max_length=40),
            preserve_default=False,
        ),
    ]
