# Generated by Django 3.1.1 on 2020-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_reference',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
    ]
