# Generated by Django 3.1.1 on 2020-10-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201001_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pid',
            new_name='stripe_pid',
        ),
    ]
