# Generated by Django 3.1.1 on 2020-10-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='No Ingredients have been added yet'),
            preserve_default=False,
        ),
    ]
